import './globals.css';
import { Space_Grotesk } from 'next/font/google'

export const metadata = {
  title: 'Connect Four',
  description: 'Generated by create next app',
}

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-purple ${spaceGrotesk.className}`}>{children}</body>
    </html>
  )
}
